# Liquibase properties for PostgreSQL
spring.liquibase.change-log=classpath:/db/changelog/db.changelog.xml
spring.datasource.url=jdbc:postgresql://localhost:5432/quizappdb
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
